githubAutomated/urls.py
from django.contrib import admin
from django.urls import path, include
from githubTool.views import home

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("githubTool/", include("githubTool.urls", namespace="githubTool"))
]

githubTool/urls.py
from django.urls import path
from . import views

app_name = "githubTool"

urlpatterns = [
    path('try/', views.try_test, name="try_test"),
    path('create/', views.create_project, name="create_project"),
]

githubTool/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    is_public = models.BooleanField(default=True)
    access_token = models.CharField(default='', max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

githubTool/forms.py
# github_automation/github_tool/forms.py

from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'is_public', 'access_token']

githubTool/views.py
from django.shortcuts import render,redirect, HttpResponseRedirect
from django.urls import reverse
from .forms import ProjectForm
from .models import Project

import requests
import shutil
import subprocess

# Create your views here.

def home(request):
    form = ProjectForm()
    return render(request, 'index.html', {'form': form})

def try_test(request):
    template_name = "tryTest.html"
    return render(request, template_name)


def create_project(request):
    if request.method == "POST":
        repo_name = request.POST.get("repo_name")
        is_private = request.POST.get("is_private") == "True"
        description = request.POST.get("description")
        access_token = request.POST.get("access_token")

        repo = Project(name=repo_name, description=description, is_public=not is_private, access_token=access_token)
        repo.save()
        
        # Call the function to create GitHub repository and handle the response
        print(create_github_repo(repo_name, is_private, description, access_token))
        print("Repository Name: ", repo_name)
        print("Is Private: ", is_private)
        print("Description: ", description)
        print("Access Token: ", access_token)
        print("Creating repository...")
        
        # Redirect to project_created view
        return HttpResponseRedirect(reverse('home') + '?visible=visible')
    else:
        redirect('home')

def create_github_repo(repo_name, is_private, description, access_token):
    url = "https://api.github.com/user/repos"
    headers = {
        "Authorization": f"token {access_token}",
        "Accept": "application/vnd.github.v3+json"
    }
    payload = {
        "name": repo_name,
        "private": is_private,
        "description": description
    }
    response = requests.post(url, json=payload, headers=headers)
    if response.status_code == 201:
        print("Repository created successfully!")
        return response.json()["clone_url"]
    else:
        print("Failed to create repository. Status code:", response.status_code)
        return None

templates/footer.html
{% load static %}

<!-- Footer -->
        <section id="footer">
            <ul class="icons">
                <li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
                <li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
                <li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
                <li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
                <li><a href="#" class="icon solid alt fa-envelope"><span class="label">Email</span></a></li>
            </ul>
            <ul class="copyright">
                <li>&copy; Untitled</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
            </ul>
        </section>

    <!-- Scripts -->
        <script src="{% static 'assets/js/jquery.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.scrolly.min.js' %}"></script>
        <script src="{% static 'assets/js/browser.min.js' %}"></script>
        <script src="{% static 'assets/js/breakpoints.min.js' %}"></script>
        <script src="{% static 'assets/js/util.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Photon by HTML5 UP</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'assets/css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Header -->
			<section id="header">
				<div class="inner">
					<span class="icon solid major fa-cloud"></span>
					<h1>Hi, I'm <strong>Photon</strong>, another fine<br />
					little freebie from <a href="http://html5up.net">HTML5 UP</a>.</h1>
					<p>Accumsan feugiat mi commodo erat lorem ipsum, sed magna<br />
					lobortis feugiat sapien sed etiam volutpat accumsan.</p>
					<ul class="actions special">
						<li><a href="#one" class="button scrolly">Discover</a></li>
					</ul>
				</div>
			</section>

templates/index.html
{% load static %}
{% include 'header.html' %}
		<!-- One -->
			<section id="one" class="main style1" style="background-color: #171515;">
				<div class="container">
					<div class="row gtr-150">
						<div class="col-6 col-12-medium">
							<header class="major">
								<h2>Lorem ipsum dolor adipiscing<br />
								amet dolor consequat</h2>
							</header>
							<form method="post" action="{% url 'githubTool:create_project' %}#one">
								{% csrf_token %}
								<div class="row gtr-uniform gtr-50">
									<div class="col-6 col-12-xsmall">
										<input type="text" name="repo_name" id="repo_name" value="" placeholder="Repo. Name"  required/>
									</div>
									<div class="col-6 col-12-xsmall">
										<input type="text" name="access_token" id="access_token" value="" placeholder="Token" required/>
									</div>
										<div class="col-4 col-12-small">
											<input type="radio" id="public" name="is_private" value="False" checked>
											<label for="public">Public</label>
										</div>
										<div class="col-4 col-12-small">
											<input type="radio" id="private" name="is_private" value="True">
											<label for="private">Private</label>
										</div>
									
									
									<div class="col-12">
										<textarea name="description" id="description" placeholder="Enter Repo Description" rows="4" required></textarea>
									</div>
									
									<div class="col-12">
										<p style="visibility: {{ request.GET.visible|default:'hidden' }};">Repo is created</p>
									</div>									
									<div class="col-12">
										<ul class="actions">
											<li><button type="submit" class="button scrolly">Done</button></li>
										</ul>
									</div>
								</div>
							</form>
							
						</div>
						<div class="col-6 col-12-medium imp-medium">
							<span class="image fit"><img src="{% static 'images/pic01.jpg' %}" alt="" /></span>
						</div>
					</div>
				</div>
			</section>

		<!-- Two -->
			<section id="two" class="main style2">
				<div class="container">
					<div class="row gtr-150">
						<div class="col-6 col-12-medium">
							<ul class="major-icons">
								<li><span class="icon solid style1 major fa-code"></span></li>
								<li><span class="icon solid style2 major fa-bolt"></span></li>
								<li><span class="icon solid style3 major fa-camera-retro"></span></li>
								<li><span class="icon solid style4 major fa-cog"></span></li>
								<li><span class="icon solid style5 major fa-desktop"></span></li>
								<li><span class="icon solid style6 major fa-calendar"></span></li>
							</ul>
						</div>
						<div class="col-6 col-12-medium">
							<header class="major">
								<h2>Lorem ipsum dolor adipiscing<br />
								amet dolor consequat</h2>
							</header>
							<p>Adipiscing a commodo ante nunc accumsan interdum mi ante adipiscing. A nunc lobortis non nisl amet vis volutpat aclacus nascetur ac non. Lorem curae eu ante amet sapien in tempus ac. Adipiscing id accumsan adipiscing ipsum.</p>
							<p>Blandit faucibus proin. Ac aliquam integer adipiscing enim non praesent vis commodo nunc phasellus cubilia ac risus accumsan. Accumsan blandit. Lobortis phasellus non lobortis dit varius mi varius accumsan lobortis. Blandit ante aliquam lacinia lorem lobortis semper morbi col faucibus vitae integer placerat accumsan orci eu mi odio tempus adipiscing adipiscing adipiscing curae consequat feugiat etiam dolore.</p>
							<p>Adipiscing a commodo ante nunc accumsan interdum mi ante adipiscing. A nunc lobortis non nisl amet vis volutpat aclacus nascetur ac non. Lorem curae eu ante amet sapien in tempus ac. Adipiscing id accumsan adipiscing ipsum.</p>
						</div>
					</div>
				</div>
			</section>

		<!-- Three -->
			<section id="three" class="main style1 special">
				<div class="container">
					<header class="major">
						<h2>Adipiscing amet consequat</h2>
					</header>
					<p>Ante nunc accumsan et aclacus nascetur ac ante amet sapien sed.</p>
					<div class="row gtr-150">
						<div class="col-4 col-12-medium">
							<span class="image fit"><img src="{% static 'images/pic02.jpg' %}" alt="" /></span>
							<h3>Magna feugiat lorem</h3>
							<p>Adipiscing a commodo ante nunc magna lorem et interdum mi ante nunc lobortis non amet vis sed volutpat et nascetur.</p>
							<ul class="actions special">
								<li><a href="#" class="button">More</a></li>
							</ul>
						</div>
						<div class="col-4 col-12-medium">
							<span class="image fit"><img src="{% static 'images/pic03.jpg' %}" alt="" /></span>
							<h3>Magna feugiat lorem</h3>
							<p>Adipiscing a commodo ante nunc magna lorem et interdum mi ante nunc lobortis non amet vis sed volutpat et nascetur.</p>
							<ul class="actions special">
								<li><a href="#" class="button">More</a></li>
							</ul>
						</div>
						<div class="col-4 col-12-medium">
							<span class="image fit"><img src="{% static 'images/pic04.jpg' %}" alt="" /></span>
							<h3>Magna feugiat lorem</h3>
							<p>Adipiscing a commodo ante nunc magna lorem et interdum mi ante nunc lobortis non amet vis sed volutpat et nascetur.</p>
							<ul class="actions special">
								<li><a href="#" class="button">More</a></li>
							</ul>
						</div>
					</div>
				</div>
			</section>

		<!-- Four -->
			<section id="four" class="main style2 special">
				<div class="container">
					<header class="major">
						<h2>Ipsum feugiat consequat?</h2>
					</header>
					<p>Sed lacus nascetur ac ante amet sapien.</p>
					<ul class="actions special">
						<li><a href="#" class="button wide primary">Sign Up</a></li>
						<li><a href="#" class="button wide">Learn More</a></li>
					</ul>
				</div>
			</section>

		<!-- Five -->
		
{% include 'footer.html' %}